POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "email": "chapengu@gmail.com",
    "username": "Chapy",
    "teamname": "PenguCorp",
    "password": "goku123"
}

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "chapengu@gmail.com",
    "password": "goku123"
}

POST http://localhost:3000/auth/logout HTTP/1.1

POST http://localhost:3000/auth/verify HTTP/1.1