POST footballbackend-production.up.railway.app/auth/register HTTP/1.1
content-type: application/json

{
    "email": "chapengu@gmail.com",
    "username": "Chapy",
    "teamname": "PenguCorp",
    "password": "goku123"
}

POST footballbackend-production.up.railway.app/auth/login HTTP/1.1
content-type: application/json

{
    "email": "chapengu@gmail.com",
    "password": "goku123"
}

POST footballbackend-production.up.railway.app/auth/login HTTP/1.1
content-type: application/json

{
    "email": "panda@gmail.com",
    "password": "panda123"
}

POST footballbackend-production.up.railway.app/auth/logout HTTP/1.1

POST footballbackend-production.up.railway.app/auth/verify HTTP/1.1