GET http://localhost:3000/player HTTP/1.1

GET http://localhost:3000/player/1 HTTP/1.1

GET http://localhost:3000/player/best-players-lastweek HTTP/1.1

GET http://localhost:3000/player/more-buy-players-lastweek HTTP/1.1

POST http://localhost:3000/player HTTP/1.1
content-type: application/json

{
    "name": "Nicolas",
    "lastname": "Rodriguez",
    "position": "MC",
    "points": 44,
    "price": 8
}

POST http://localhost:3000/player/valoration/1 HTTP/1.1
content-type: application/json

{
    "userId": 1,
    "valoration": 5
}

PUT http://localhost:3000/player/statistics/8 HTTP/1.1
content-type: application/json

{
    "goals": 10
}