GET http://localhost:3000/user HTTP/1.1

GET http://localhost:3000/user/1 HTTP/1.1

GET http://localhost:3000/user/weeks/1 HTTP/1.1

###

POST http://localhost:3000/user/transfer/1 HTTP/1.1
Content-Type: application/json

{
    "players": [
        {
            "id": 11,
            "isBanking": false,
            "order": 0,
            "isCaptain": true,
        },
        {
            "id": 2,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 3,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 4,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 5,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 6,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 7,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 8,
            "isBanking": true,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 9,
            "isBanking": true,
            "order": 0,
            "isCaptain": false
        }
    ]
}

###

PUT http://localhost:3000/user/change/1 HTTP/1.1
Content-Type: application/json

{
    "players": [
        {
            "id": 1,
            "isBanking": false,
            "order": 0,
            "isCaptain": true
        },
        {
            "id": 2,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 3,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 4,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 5,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 6,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 7,
            "isBanking": false,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 8,
            "isBanking": true,
            "order": 0,
            "isCaptain": false
        },
        {
            "id": 9,
            "isBanking": true,
            "order": 0,
            "isCaptain": false
        }
    ]
}

###

PATCH http://localhost:3000/user/captain/1 HTTP/1.1
Content-Type: application/json

{
    "playerId": 8
}