GET http://localhost:3000/user HTTP/1.1

GET http://localhost:3000/user/1 HTTP/1.1

###

POST http://localhost:3000/user/add-player-align/1 HTTP/1.1
Content-Type: application/json

{
    "playerId": 8
}

###

POST http://localhost:3000/user/add-player-banking/1 HTTP/1.1
Content-Type: application/json

{
    "playerId": 10
}

###

PUT http://localhost:3000/user/change-align-align/1 HTTP/1.1
Content-Type: application/json

{
    "playerAId": 1,
    "playerBId": 2
}

PUT http://localhost:3000/user/change-banking-banking/1 HTTP/1.1
Content-Type: application/json

{
    "playerAId": 11,
    "playerBId": 12
}

PUT http://localhost:3000/user/change-align-banking/1 HTTP/1.1
Content-Type: application/json

{
    "playerOnAlignId": 13,
    "playerOnBankingId": 11
}

PUT http://localhost:3000/user/change-captain/1 HTTP/1.1
Content-Type: application/json

{
    "playerId": 8
}

###

GET http://localhost:3000/user/weeks/1 HTTP/1.1

###